### ISSUE TITLE
connection closed with error message

### ISSUE THREAD

**Issue by ornariece** [TKMAX777/RemoteRelativeInput#3]
hi, trying to connect from windows to windows here.
after initiating the ssh connection, then pressing "Yes" on the host, then "OK" on the client, the connection closes and i get this error message on the client:
![image](https://user-images.githubusercontent.com/25489980/185967930-548444b2-9f90-4f14-9baa-08dee2a744c2.png)

**Comment by TKMAX777** [comment]
You have to open RDP client first, then set a window name environment variable, and run program.

```
set CLIENT_NAME=<HostAddress> - Remote Desktop Connection
RelativeInputClient.exe | ssh <HostUsername>@<HostAddress> "C:\Users\<HostFolderName>\go\bin\RelativeInputServer.exe"
```

Here, CLIENT_NAME must be RDP client window name, like "192.168.1.24 - Remote Desktop Connection"

**Comment by ornariece** [comment]
i've done exactly that though

**Comment by TKMAX777** [comment]
NilWindowHandler error occurs when put titled window is not found.
Maybe the put window title does not match. 

For example, "192.168.1.24 - Remote Desktop Connection" changes depending on the language environment, like "192.168.1.24 - リモート デスクトップ接続" on Japanese settings. 

In addition, the title of the remote desktop window may be in the format "PC name - Remote Desktop Connection" instead of "192.168.***. *** - Remote Desktop Connection". 
　
Do the configured environment variables match, including these one?

If all is well, could you show me the environment variables you have set?

**Comment by ornariece** [comment]
well turns out i don't need the double quotes around the environment variable's value (btw there's a typo in your README, there's a single double quote at the end of the line). thanks for the help, much appreciated!

out of topic: any plan to port the client-side part to linux? i'm using the freerdp client and i'd love to use your tool from my linux laptop.

**Comment by TKMAX777** [comment]
Thank you for pointing this out. It has been corrected.

#4 

Sorry, but I have no plans to create a client for the Linux side at this time.

I may implement it someday if I have time, but I think it will be much later.

Of course, contributions are welcome.
